const canvas=document.getElementById('game');
const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;const W=480,H=270;const world={w:1400,h:900};
const player={x:700,y:450,r:10,speed:115,hp:100,maxHp:100,angle:0,ammo:12,mag:12,reserve:60,reloading:false,dodgeCooldown:0,invuln:0,dodgeVX:0,dodgeVY:0};const camera={x:0,y:0};let running=false,paused=false,last=0,shootHeld=false,shootCooldown=0,lootOpen=false,currentCrate=null,gameOverTimer=null;let enemies=[],bullets=[],particles=[],crates=[];
const inv={Scrap:0,'9mm Ammo':60,'12 Gauge':0,'5.56 Ammo':0,'7.62 Ammo':0,'Energy Cell':0,'Canned Food':0,Medkit:0,Weapons:0};const ownedWeapons=[];
const RARITIES=[{name:'Common',weight:54},{name:'Uncommon',weight:24},{name:'Epic',weight:11},{name:'Legendary',weight:6},{name:'Mythic',weight:3},{name:'Secret',weight:1},{name:'Special',weight:1}];
const WEAPONS=[{name:'Rust Pistol',rarities:['Common'],ammo:'9mm Ammo'},{name:'Service Pistol',rarities:['Common','Uncommon'],ammo:'9mm Ammo'},{name:'Combat SMG',rarities:['Uncommon','Epic'],ammo:'9mm Ammo'},{name:'Pump Shotgun',rarities:['Uncommon','Epic'],ammo:'12 Gauge'},{name:'Assault Rifle',rarities:['Epic','Legendary'],ammo:'5.56 Ammo'},{name:'Marksman Rifle',rarities:['Epic','Legendary'],ammo:'7.62 Ammo'},{name:'Thunderbolt AR',rarities:['Legendary','Mythic'],ammo:'5.56 Ammo'},{name:'Wasteland Reaper',rarities:['Mythic'],ammo:'7.62 Ammo'},{name:'ARGUS Prototype',rarities:['Secret'],ammo:'Energy Cell'},{name:'Ashen Nova',rarities:['Special'],ammo:'Energy Cell'}];
const AMMO={'9mm Ammo':{min:8,max:30},'12 Gauge':{min:4,max:16},'5.56 Ammo':{min:10,max:32},'7.62 Ammo':{min:8,max:24},'Energy Cell':{min:4,max:18}};const CONSUMABLES=[{name:'Scrap',min:4,max:14},{name:'Canned Food',min:1,max:4},{name:'Medkit',min:1,max:2}];
let cratesOpened=0;const keys={};addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key===' ')e.preventDefault()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
const joystick={active:false,id:null,x:0,y:0};const joy=document.getElementById('joystick'),stick=document.getElementById('stick');
function joyPoint(e){const r=joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;let x=e.clientX-cx,y=e.clientY-cy,m=Math.hypot(x,y),max=Math.max(30,r.width*.36);if(m>max){x=x/m*max;y=y/m*max}joystick.x=x/max;joystick.y=y/max;stick.style.transform=`translate(${x}px,${y}px)`}
joy.addEventListener('pointerdown',e=>{e.preventDefault();joystick.active=true;joystick.id=e.pointerId;joy.setPointerCapture(e.pointerId);joyPoint(e)});joy.addEventListener('pointermove',e=>{if(joystick.active&&e.pointerId===joystick.id)joyPoint(e)});['pointerup','pointercancel'].forEach(t=>joy.addEventListener(t,e=>{if(e.pointerId===joystick.id){joystick.active=false;joystick.x=joystick.y=0;stick.style.transform=''}}));

/* One visible right-hand control now handles both aiming and firing.
   Drag the red fire button away from its center to change player.angle. */
const shoot=document.getElementById('shoot');const fireStick={active:false,id:null};
function firePoint(e){const r=shoot.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;let x=e.clientX-cx,y=e.clientY-cy,m=Math.hypot(x,y),max=Math.max(22,r.width*.34);if(m>max){x=x/m*max;y=y/m*max}if(m>5)player.angle=Math.atan2(y,x);shoot.style.setProperty('--aim-x',`${x}px`);shoot.style.setProperty('--aim-y',`${y}px`)}
shoot.addEventListener('pointerdown',e=>{if(paused||lootOpen||!running)return;e.preventDefault();fireStick.active=true;fireStick.id=e.pointerId;shoot.setPointerCapture(e.pointerId);firePoint(e);shootHeld=true;fire()});
shoot.addEventListener('pointermove',e=>{if(fireStick.active&&e.pointerId===fireStick.id)firePoint(e)});
['pointerup','pointercancel'].forEach(t=>shoot.addEventListener(t,e=>{if(e.pointerId===fireStick.id){fireStick.active=false;fireStick.id=null;shootHeld=false;shoot.style.setProperty('--aim-x','0px');shoot.style.setProperty('--aim-y','0px')}}));

document.getElementById('reload').onclick=reload;document.getElementById('dodge').onclick=dodge;document.getElementById('interact').onclick=interact;document.getElementById('inventory-btn').onclick=()=>togglePanel('inventory-panel');document.getElementById('pause-btn').onclick=()=>{paused=true;togglePanel('pause-panel')};document.getElementById('resume').onclick=()=>{paused=false;togglePanel('pause-panel')};document.getElementById('close-inventory').onclick=()=>togglePanel('inventory-panel');document.getElementById('close-loot').onclick=closeLoot;document.getElementById('take-all').onclick=takeAll;document.getElementById('start').onclick=()=>{document.getElementById('start-screen').style.display='none';reset();running=true;showMessage('Explore, loot, and hunt for rare gear.')};
function reset(){if(gameOverTimer){clearTimeout(gameOverTimer);gameOverTimer=null}player.x=700;player.y=450;player.hp=100;player.ammo=12;player.reserve=60;player.reloading=false;player.dodgeCooldown=0;player.invuln=0;player.dodgeVX=0;player.dodgeVY=0;cratesOpened=0;enemies=[enemy(480,330),enemy(880,320),enemy(980,570),enemy(590,650),enemy(1080,470),enemy(300,260),enemy(1250,300),enemy(240,720)];crates=makeCrates(18);currentCrate=null;ownedWeapons.length=0;Object.keys(inv).forEach(k=>inv[k]=0);inv['9mm Ammo']=60;inv.Weapons=0;inventoryHTML='';updateInventory();updateHud()}
function makeCrates(count){const positions=[];for(let i=0;i<count;i++){let x,y,tries=0;do{x=70+Math.random()*(world.w-140);y=70+Math.random()*(world.h-140);tries++}while(positions.some(p=>Math.hypot(p.x-x,p.y-y)<75)&&tries<100);positions.push({x,y,open:false,loot:null})}return positions}
function enemy(x,y){return{x,y,r:9,hp:45,maxHp:45,speed:42,hit:0}}function worldToScreen(x,y){return{x:x-camera.x,y:y-camera.y}}
function chooseRarity(forceMin=0){const order=['Common','Uncommon','Epic','Legendary','Mythic','Secret','Special'];let pool=RARITIES.filter(r=>order.indexOf(r.name)>=forceMin);const total=pool.reduce((s,r)=>s+r.weight,0);let roll=Math.random()*total;for(const r of pool){roll-=r.weight;if(roll<=0)return r}return pool[0]}
function makeLoot(){const pity8=cratesOpened>0&&cratesOpened%8===0,pity20=cratesOpened>0&&cratesOpened%20===0;let count=4+Math.floor(Math.random()*5),items=[];for(let i=0;i<count;i++){let rarity=chooseRarity(pity20?3:pity8?2:0),roll=Math.random();if(roll<.28){const c=CONSUMABLES[Math.floor(Math.random()*CONSUMABLES.length)],qty=c.min+Math.floor(Math.random()*(c.max-c.min+1));items.push({type:'item',name:c.name,qty,rarity})}else if(roll<.62){const names=Object.keys(AMMO),name=names[Math.floor(Math.random()*names.length)],cfg=AMMO[name],qty=cfg.min+Math.floor(Math.random()*(cfg.max-cfg.min+1));items.push({type:'ammo',name,qty,rarity})}else{let choices=WEAPONS.filter(w=>w.rarities.includes(rarity.name));if(!choices.length)choices=WEAPONS.filter(w=>w.rarities.includes('Common'));const weapon=choices[Math.floor(Math.random()*choices.length)];const finalRarity=weapon.rarities.includes(rarity.name)?rarity:{name:'Common'};items.push({type:'weapon',name:weapon.name,qty:1,rarity:finalRarity,ammo:weapon.ammo})}}
if(!items.some(i=>i.type==='ammo')){const name='9mm Ammo',qty=10+Math.floor(Math.random()*21);items[0]={type:'ammo',name,qty,rarity:{name:'Common'}}}return items}
function rarityColor(name){return({Common:'#d3d6d8',Uncommon:'#69c875',Epic:'#bc7bf1',Legendary:'#f1a24b',Mythic:'#e754d8',Secret:'#44d8ef',Special:'#ffe66b'})[name]||'#fff'}
function fire(){if(!running||paused||lootOpen||player.reloading||shootCooldown>0)return;if(player.ammo<=0){showMessage('OUT OF AMMO — tap reload');return}player.ammo--;shootCooldown=.18;const a=player.angle;bullets.push({x:player.x+Math.cos(a)*12,y:player.y+Math.sin(a)*12,vx:Math.cos(a)*420,vy:Math.sin(a)*420,life:1.1});burst(player.x+Math.cos(a)*12,player.y+Math.sin(a)*12,4);updateHud()}
function reload(){if(player.reloading||player.ammo===player.mag||player.reserve<=0)return;player.reloading=true;showMessage('Reloading...');setTimeout(()=>{if(!player.reloading)return;const n=Math.min(player.mag-player.ammo,player.reserve);player.ammo+=n;player.reserve-=n;inv['9mm Ammo']=player.reserve;player.reloading=false;updateHud();showMessage('Reloaded')},650)}
function dodge(){if(!running||paused||lootOpen||player.dodgeCooldown>0)return;let m=moveInput(),dx=m.x,dy=m.y;if(!dx&&!dy){dx=Math.cos(player.angle);dy=Math.sin(player.angle)}player.invuln=.34;player.dodgeCooldown=1;player.dodgeVX=dx*380;player.dodgeVY=dy*380;showMessage('DODGE!');updateHud()}
function moveInput(){let x=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),y=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);if(joystick.active){x=joystick.x;y=joystick.y}const m=Math.hypot(x,y);return m>0?{x:x/m,y:y/m}:{x:0,y:0}}
function nearestEnemy(){let best=null,bd=Infinity;for(const e of enemies){if(e.hp<=0)continue;const d=Math.hypot(e.x-player.x,e.y-player.y);if(d<bd){bd=d;best=e}}return best}
function update(dt){if(!running||paused)return;shootCooldown=Math.max(0,shootCooldown-dt);player.dodgeCooldown=Math.max(0,player.dodgeCooldown-dt);player.invuln=Math.max(0,player.invuln-dt);const m=moveInput();let vx=m.x*player.speed,vy=m.y*player.speed;if(player.invuln){vx+=player.dodgeVX;vy+=player.dodgeVY;player.dodgeVX*=Math.pow(.04,dt);player.dodgeVY*=Math.pow(.04,dt)}player.x=Math.max(20,Math.min(world.w-20,player.x+vx*dt));player.y=Math.max(20,Math.min(world.h-20,player.y+vy*dt));if(!fireStick.active){const target=nearestEnemy();if(target)player.angle=Math.atan2(target.y-player.y,target.x-player.x)}if(shootHeld)fire();for(const b of bullets){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.life<=0)continue;for(const e of enemies){if(e.hp>0&&Math.hypot(b.x-e.x,b.y-e.y)<e.r+3){e.hp-=25;b.life=0;e.hit=.08;burst(e.x,e.y,5);if(e.hp<=0){inv.Scrap+=3;showMessage('+3 SCRAP');updateInventory()}break}}}bullets=bullets.filter(b=>b.life>0&&b.x>0&&b.y>0&&b.x<world.w&&b.y<world.h);for(const e of enemies){if(e.hp<=0)continue;e.hit=Math.max(0,e.hit-dt);const dx=player.x-e.x,dy=player.y-e.y,d=Math.hypot(dx,dy)||1;if(d>22){e.x+=dx/d*e.speed*dt;e.y+=dy/d*e.speed*dt}if(d<24&&player.invuln<=0)player.hp-=18*dt}for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt}particles=particles.filter(p=>p.life>0);camera.x=Math.max(0,Math.min(world.w-W,player.x-W/2));camera.y=Math.max(0,Math.min(world.h-H,player.y-H/2));if(player.hp<=0&&!gameOverTimer){player.hp=0;showMessage('You were overwhelmed — restarting...');gameOverTimer=setTimeout(()=>{gameOverTimer=null;reset()},900)}updateHud()}
function draw(){ctx.clearRect(0,0,W,H);drawWorld();drawCrates();drawBullets();drawEnemies();drawPlayer();drawParticles()}
function drawWorld(){ctx.fillStyle='#26382b';ctx.fillRect(0,0,W,H);const sx=Math.floor(camera.x/32)*32,sy=Math.floor(camera.y/32)*32;for(let y=sy;y<camera.y+H+32;y+=32)for(let x=sx;x<camera.x+W+32;x+=32){const px=x-camera.x,py=y-camera.y;ctx.fillStyle=((x/32+y/32)%2===0)?'#2a3b2e':'#2d4032';ctx.fillRect(px,py,31,31)}ctx.fillStyle='#343a38';ctx.fillRect(0,220-camera.y,W,70);ctx.fillRect(635-camera.x,0,78,900);for(const b of [[80,90,150,85],[880,90,170,100],[1050,650,190,120],[160,700,150,100]]){const[x,y,w,h]=b;ctx.fillStyle='#4a4b46';ctx.fillRect(x-camera.x,y-camera.y,w,h);ctx.fillStyle='#242b29';for(let xx=x+15;xx<x+w-10;xx+=35)ctx.fillRect(xx-camera.x,y+18-camera.y,18,20)}for(const t of [[120,350],[200,470],[1130,470],[1250,180],[360,170],[1180,780],[420,760],[1010,430]]){const[x,y]=t;ctx.fillStyle='#16261c';ctx.fillRect(x-3-camera.x,y+5-camera.y,6,15);ctx.fillStyle='#102117';ctx.fillRect(x-12-camera.x,y-10-camera.y,24,20);ctx.fillRect(x-18-camera.x,y-camera.y,36,14)}}
function drawPlayer(){const p=worldToScreen(player.x,player.y);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(player.angle);ctx.fillStyle=player.invuln?'#e8f3f3':'#d9b47a';ctx.fillRect(-7,-8,14,16);ctx.fillStyle='#38454a';ctx.fillRect(3,-3,13,6);ctx.fillStyle='#10181b';ctx.fillRect(-5,-11,10,5);ctx.restore()}
function drawEnemies(){for(const e of enemies)if(e.hp>0){const p=worldToScreen(e.x,e.y);ctx.fillStyle=e.hit?'#fff':'#9d493f';ctx.fillRect(p.x-8,p.y-8,16,16);ctx.fillStyle='#201517';ctx.fillRect(p.x-5,p.y-4,10,4);ctx.fillStyle='#171c1a';ctx.fillRect(p.x-10,p.y-14,20,3);ctx.fillStyle='#7fce66';ctx.fillRect(p.x-10,p.y-14,20*Math.max(0,e.hp/e.maxHp),3)}}
function drawCrates(){for(const c of crates){if(c.open)continue;const p=worldToScreen(c.x,c.y);ctx.fillStyle='#8c6337';ctx.fillRect(p.x-10,p.y-8,20,16);ctx.fillStyle='#c49a5a';ctx.fillRect(p.x-2,p.y-8,4,16)}}
function drawBullets(){ctx.fillStyle='#f3d28b';for(const b of bullets){const p=worldToScreen(b.x,b.y);ctx.fillRect(p.x-2,p.y-2,4,4)}}
function burst(x,y,n){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=30+Math.random()*70;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.25})}}
function drawParticles(){ctx.fillStyle='#e1ad64';for(const p of particles){const s=2+3*p.life/.25,q=worldToScreen(p.x,p.y);ctx.fillRect(q.x-s/2,q.y-s/2,s,s)}}
function nearbyCrate(){return crates.find(c=>!c.open&&Math.hypot(c.x-player.x,c.y-player.y)<50)||null}
function interact(){if(lootOpen)return;const c=nearbyCrate();if(!c){showMessage('Move closer to a crate');return}openLoot(c)}
function openLoot(c){currentCrate=c;lootOpen=true;cratesOpened++;c.loot=makeLoot();document.getElementById('loot-panel').classList.remove('hidden');document.getElementById('interact').classList.add('hidden');document.getElementById('loot-list').innerHTML=c.loot.map(item=>`<div class="loot-row"><span>${item.type==='weapon'?'🔫':item.type==='ammo'?'💥':'🎒'} ${item.name} <span class="rarity" style="color:${rarityColor(item.rarity.name)}">${item.rarity.name}</span></span><b>x${item.qty}</b></div>`).join('')}
function takeAll(){if(!currentCrate)return;for(const item of currentCrate.loot){if(item.type==='weapon'){ownedWeapons.push({name:item.name,rarity:item.rarity.name,ammo:item.ammo});inv.Weapons++}else inv[item.name]=(inv[item.name]||0)+item.qty}currentCrate.open=true;currentCrate.loot=null;currentCrate=null;closeLoot();showMessage('Loot collected');updateHud()}
function closeLoot(){lootOpen=false;currentCrate=null;document.getElementById('loot-panel').classList.add('hidden');updateHud()}
function togglePanel(id){document.getElementById(id).classList.toggle('hidden')}
let inventoryHTML='';function updateInventory(){const rows=Object.entries(inv).map(([k,v])=>`<div class="inv-row"><span>${k}</span><b>${v}</b></div>`).join('');const weapons=ownedWeapons.map(w=>`<div class="inv-row"><span>🔫 ${w.name} <small style="color:${rarityColor(w.rarity)}">${w.rarity}</small></span><b>1</b></div>`).join('');const next=rows+weapons;if(next!==inventoryHTML){inventoryHTML=next;document.getElementById('inventory-list').innerHTML=next}}
let lastHp=-1,lastAmmo=-1,lastReserve=-1,lastDodge=-1,lastNear=false;
function updateHud(){const hp=Math.ceil(player.hp);if(hp!==lastHp){lastHp=hp;document.getElementById('hp-fill').style.width=`${Math.max(0,player.hp/player.maxHp*100)}%`;document.getElementById('hp-text').textContent=`${hp}/${player.maxHp}`}if(player.ammo!==lastAmmo||player.reserve!==lastReserve){lastAmmo=player.ammo;lastReserve=player.reserve;document.getElementById('ammo-text').textContent=`${player.ammo}/${player.reserve}`}const dodge=document.getElementById('dodge');if(player.dodgeCooldown>0){const sec=Math.ceil(player.dodgeCooldown);if(lastDodge!==sec){dodge.textContent=sec;lastDodge=sec}dodge.classList.add('cooling')}else{if(lastDodge!==0){dodge.textContent='↯';lastDodge=0}dodge.classList.remove('cooling')}const near=!!nearbyCrate();if(near!==lastNear){lastNear=near;document.getElementById('interact').classList.toggle('hidden',!near||lootOpen)}else if(lootOpen)document.getElementById('interact').classList.add('hidden');updateInventory()}
let msgTimer=0;function showMessage(t){const el=document.getElementById('message');el.textContent=t;el.style.opacity=1;clearTimeout(msgTimer);msgTimer=setTimeout(()=>el.style.opacity=0,1300)}
requestAnimationFrame(function loop(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)});updateInventory();updateHud();