/* Frontier Ashes — Phase 2.5: rarity-aware field armory UI. */
(function(){
  const BASE={'Rust Pistol':{mag:12,damage:25,fireRate:.18,bulletSpeed:420},'Service Pistol':{mag:15,damage:27,fireRate:.16,bulletSpeed:430},'Combat SMG':{mag:30,damage:19,fireRate:.085,bulletSpeed:440},'Pump Shotgun':{mag:6,damage:45,fireRate:.55,bulletSpeed:360},'Assault Rifle':{mag:30,damage:28,fireRate:.11,bulletSpeed:500},'Marksman Rifle':{mag:8,damage:55,fireRate:.48,bulletSpeed:650},'Thunderbolt AR':{mag:36,damage:32,fireRate:.095,bulletSpeed:530},'Wasteland Reaper':{mag:10,damage:72,fireRate:.38,bulletSpeed:620},'ARGUS Prototype':{mag:20,damage:64,fireRate:.13,bulletSpeed:560},'Ashen Nova':{mag:24,damage:78,fireRate:.105,bulletSpeed:600}};
  const R={Common:1,Uncommon:1.08,Epic:1.18,Legendary:1.30,Mythic:1.44,Secret:1.60,Special:1.78};
  const rarityColor=name=>({Common:'#d3d6d8',Uncommon:'#69c875',Epic:'#bc7bf1',Legendary:'#f1a24b',Mythic:'#e754d8',Secret:'#44d8ef',Special:'#ffe66b'})[name]||'#fff';
  const calc=w=>{const b=BASE[w&&w.name]||BASE['Rust Pistol'],m=R[w&&w.rarity]||1;return{mag:Math.max(1,Math.round(b.mag*(1+(m-1)*.55))),damage:Math.round(b.damage*m),fireRate:Math.max(.045,b.fireRate*(1-(m-1)*.20)),bulletSpeed:Math.round(b.bulletSpeed*(1+(m-1)*.35))}};
  let slots=[null,null],activeSlot=0,initialized=false;
  const style=document.createElement('style');style.textContent=`#gun-loadout-panel{position:absolute;inset:0;z-index:60;display:none;place-items:center;background:#05090ced;padding:14px}.gun-card{width:min(94vw,640px);max-height:88vh;overflow:auto;background:#10171b;border:2px solid #68757a;box-shadow:0 16px 60px #000;padding:16px}.gun-card h2{margin:2px 0 10px;font-size:22px}.gun-kicker{font-size:8px;letter-spacing:2px;color:#879396}.gun-slots{display:grid;grid-template-columns:1fr 1fr;gap:8px}.gun-slot{background:#172125;border:2px solid #39464a;padding:10px;min-height:86px}.gun-slot.active{border-color:#d36b63;background:#251719}.gun-slot b{display:block;font-size:12px}.gun-slot small{display:block;color:#aeb8ba;margin-top:4px}.gun-slot button{margin-top:8px;width:100%}.gun-actions{margin-top:10px}.gun-card button{background:#1d292d;color:#fff;border:2px solid #536168;border-radius:6px;padding:9px;font-weight:900}.gun-card .primary{background:#713732;border-color:#d36b63}.gun-backpack{margin-top:10px;padding:10px;background:#0c1316;border:1px solid #39464a}.gun-backpack-row{display:grid;grid-template-columns:1fr auto;align-items:center;gap:8px;padding:8px 0;border-bottom:1px solid #263338}.gun-backpack-row:last-child{border-bottom:0}.gun-backpack-row b{display:block;font-size:11px}.gun-backpack-row small{color:#aeb8ba}.gun-backpack-row button{padding:6px 9px}.gun-loot{margin-top:10px;padding:10px;background:#0c1316;border:1px solid #39464a}.gun-loot-row{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:8px 0;border-bottom:1px solid #263338}.gun-loot-row:last-child{border-bottom:0}.gun-loot-row button{padding:6px 9px}.raid-weapons-box{margin-top:10px;padding:10px;background:#0c1316;border:1px solid #39464a}.raid-weapon-row{display:flex;justify-content:space-between;align-items:center;gap:8px;padding:7px 0;border-bottom:1px solid #263338}.raid-weapon-row:last-child{border-bottom:0}.raid-weapon-row small{display:block;color:#aeb8ba}.gun-statline{display:flex;flex-wrap:wrap;gap:5px;margin-top:6px}.gun-stat{font-size:9px;padding:3px 5px;background:#0c1316;border:1px solid #39464a;color:#d9e0e1}.gun-rarity{font-size:9px;letter-spacing:1px;text-transform:uppercase}`;document.head.appendChild(style);
  const panel=document.createElement('div');panel.id='gun-loadout-panel';panel.innerHTML=`<div class="gun-card"><span class="gun-kicker">FIELD ARMORY · RAID LOADOUT</span><h2>GUN LOADOUT</h2><div class="gun-slots" id="gun-slots"></div><div class="gun-backpack" id="gun-backpack"></div><div class="gun-loot" id="gun-loot"></div><div class="gun-actions"><button id="gun-close">CLOSE</button></div></div>`;document.getElementById('game-shell').appendChild(panel);
  const name=w=>w&&w.name?w.name:'Unknown Weapon',ammo=w=>w&&w.ammo?w.ammo:'9mm Ammo';
  const makeWeapon=item=>({id:`raidgun-${Date.now()}-${Math.random().toString(36).slice(2,9)}`,name:item.name,rarity:item.rarity?.name||item.rarity||'Common',ammo:ammo(item),magAmmo:Number(item.magAmmo)||0,reserve:Number(item.reserve)||0,insured:false});
  function ensureRaid(){if(!raidInventory)return false;if(!Array.isArray(raidInventory.weapons))raidInventory.weapons=[];return true}
  function ensureState(){if(!ensureRaid()||initialized)return;const starter=loadout&&loadout.weapon?{id:`insured-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,name:loadout.weapon.name,rarity:loadout.weapon.rarity||'Common',ammo:loadout.ammoType||loadout.weapon.ammo||'9mm Ammo',magAmmo:Number(player.ammo)||0,reserve:Number(player.reserve)||Number(loadout.ammo)||0,insured:true}:null;raidInventory.weapons=starter?[starter]:[];slots=[starter?starter.id:null,null];activeSlot=0;initialized=true}
  function find(id){return raidInventory.weapons.find(w=>w.id===id)||null}function sync(w){if(w){w.magAmmo=Math.max(0,Number(player.ammo)||0);w.reserve=Math.max(0,Number(player.reserve)||0)}}function syncActive(){const w=find(slots[activeSlot]);if(w)sync(w)}
  function equip(index){ensureState();const w=find(slots[index]);if(!w)return;syncActive();activeSlot=index;loadout={weapon:{...w},ammoType:ammo(w),ammo:Number(w.magAmmo)||0,insured:!!w.insured};const s=window.FrontierAshesWeaponStats?.stats?.()||calc(w);player.mag=s.mag;player.ammo=Math.max(0,Math.min(s.mag,Number(w.magAmmo)||0));player.ammoType=ammo(w);player.reserve=Math.max(0,Number(w.reserve)||Number(inv[player.ammoType]||0));inv[player.ammoType]=player.reserve;const card=document.querySelector('.weapon-card b');if(card)card.textContent=name(w).toUpperCase();updateHud();updateInventory();render();renderMainInventory();showMessage('Equipped '+name(w)+'.')}
  function add(item){ensureState();const w=makeWeapon(item);raidInventory.weapons.push(w);inv.Weapons=Math.max(0,Number(inv.Weapons)||0)+1;const free=slots.findIndex(id=>!id);if(free>=0){slots[free]=w.id;equip(free)}renderMainInventory();return w}
  function pickup(item){if(!item||item.type!=='weapon')return null;const w=add(item);showMessage('Stored '+name(w)+' in raid backpack.');render();return w}
  function swapIntoSlot(id,targetSlot){ensureState();const w=find(id);if(!w)return false;const oldId=slots[targetSlot];const old=find(oldId);if(oldId===id)return true;syncActive();if(old&&oldId!==id)sync(old);slots[targetSlot]=id;activeSlot=targetSlot;equip(targetSlot);showMessage(old?`Swapped ${name(old)} for ${name(w)}.`:`Equipped ${name(w)}.`);return true}
  function render(){ensureState();const se=document.getElementById('gun-slots');se.innerHTML=slots.map((id,i)=>{const w=find(id);if(!w)return `<div class="gun-slot"><b>${i?'SECONDARY':'PRIMARY'} · EMPTY</b><small>Use EQUIP on a carried gun to fill this slot.</small></div>`;const s=calc(w);return `<div class="gun-slot ${i===activeSlot?'active':''}"><b>${i?'SECONDARY':'PRIMARY'} · ${name(w)}</b><small class="gun-rarity" style="color:${rarityColor(w.rarity)}">${w.rarity}${w.insured?' · INSURED':''}</small><small>${ammo(w)} · ${Number(w.magAmmo)||0}/${Number(w.reserve)||0}</small><div class="gun-statline"><span class="gun-stat">DMG ${s.damage}</span><span class="gun-stat">MAG ${s.mag}</span><span class="gun-stat">ROF ${s.fireRate.toFixed(2)}s</span></div><button data-equip="${i}">${i===activeSlot?'EQUIPPED':'EQUIP'}</button></div>`}).join('');se.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>equip(Number(b.dataset.equip)));
    const bp=raidInventory.weapons||[],be=document.getElementById('gun-backpack'),full=slots[0]&&slots[1];be.innerHTML=`<b>RAID BACKPACK · ${bp.length} GUN${bp.length===1?'':'S'}</b>`+(bp.length?bp.map(w=>{const si=slots.indexOf(w.id);const s=calc(w);const label=si>=0?'EQUIPPED':(full?'SWAP':'EQUIP');return `<div class="gun-backpack-row"><span><b>${name(w)}</b><small style="color:${rarityColor(w.rarity)}">${w.rarity}${si>=0?' · '+(si?'SECONDARY':'PRIMARY'):''}</small><small>DMG ${s.damage} · MAG ${s.mag}</small></span><button data-equip-id="${w.id}" class="primary">${label}</button></div>`}).join(''):'<small>No guns stored yet. TAKE ALL will save every gun you loot here.</small>');be.querySelectorAll('[data-equip-id]').forEach(b=>b.onclick=()=>{const id=b.dataset.equipId,si=slots.indexOf(id);if(si>=0){equip(si);return}const free=slots.findIndex(x=>!x);if(free>=0){slots[free]=id;equip(free)}else{swapIntoSlot(id,activeSlot)}});
    const loot=currentCrate&&Array.isArray(currentCrate.loot)?currentCrate.loot.filter(x=>x.type==='weapon'):[],le=document.getElementById('gun-loot');le.innerHTML=loot.length?`<b>WEAPONS IN CURRENT CACHE</b>`+loot.map((w,i)=>{const s=calc(w);return `<div class="gun-loot-row"><span>🔫 ${name(w)}<small style="color:${rarityColor(w.rarity?.name||w.rarity)}"> ${w.rarity?.name||w.rarity} · DMG ${s.damage} · MAG ${s.mag}</small></span><button data-pick="${i}" class="primary">STORE</button></div>`}).join(''):'<small>No weapon is currently highlighted. Open a supply crate to find guns.</small>';le.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>{if(!currentCrate||!Array.isArray(currentCrate.loot))return;const ws=currentCrate.loot.filter(x=>x.type==='weapon'),item=ws[Number(b.dataset.pick)];if(!item)return;pickup(item);const i=currentCrate.loot.indexOf(item);if(i>=0)currentCrate.loot.splice(i,1);render()})}
  function renderMainInventory(){const invp=document.getElementById('inventory-panel');if(!invp||!ensureRaid())return;let box=document.getElementById('raid-weapons-box');if(!box){box=document.createElement('div');box.id='raid-weapons-box';box.className='raid-weapons-box';const close=invp.querySelector('#close-inventory');invp.insertBefore(box,close||null)}const bp=raidInventory.weapons||[];box.innerHTML=`<b>RAID GUNS · ${bp.length}</b>`+(bp.length?bp.map(w=>{const s=calc(w);return `<div class="raid-weapon-row"><span>🔫 ${name(w)}<small style="color:${rarityColor(w.rarity)}">${w.rarity}${slots.includes(w.id)?' · EQUIPPED':''} · DMG ${s.damage} · MAG ${s.mag}</small></span><span>${Number(w.magAmmo)||0}/${Number(w.reserve)||0}</span></div>`}).join(''):'<small>No guns in your raid backpack.</small>')}
  function open(){if(!running)return;ensureState();syncActive();render();panel.style.display='grid';paused=true}function close(){panel.style.display='none';paused=false;renderMainInventory()}document.getElementById('gun-close').onclick=close;
  const invBtn=document.getElementById('inventory-btn');if(invBtn){const wrap=document.createElement('button');wrap.className='hud-btn';wrap.id='gun-loadout-btn';wrap.textContent='🔫';wrap.setAttribute('aria-label','Gun Loadout');invBtn.parentNode.insertBefore(wrap,invBtn.nextSibling);invBtn.addEventListener('click',()=>renderMainInventory());wrap.onclick=open}
  const take=document.getElementById('take-all');if(take)take.onclick=()=>{if(!currentCrate||!Array.isArray(currentCrate.loot))return;ensureState();const loot=[...currentCrate.loot];let guns=0;for(const item of loot){if(item.type==='weapon'){pickup(item);guns++;continue}if(item.type==='ammo'){inv[item.name]=(Number(inv[item.name])||0)+Number(item.qty||0);raidInventory.ammo[item.name]=(Number(raidInventory.ammo[item.name])||0)+Number(item.qty||0);continue}if(item.type==='item'){inv[item.name]=(Number(inv[item.name])||0)+Number(item.qty||0);raidInventory.items[item.name]=(Number(raidInventory.items[item.name])||0)+Number(item.qty||0)}}currentCrate.loot=[];currentCrate.open=true;updateInventory();renderMainInventory();closeLoot();showMessage(guns?`Loot secured · ${guns} gun${guns===1?'':'s'} stored.`:'Loot secured.')};
  const lp=document.getElementById('loot-panel');if(lp){const btn=document.createElement('button');btn.className='secondary';btn.textContent='GUN LOADOUT';btn.onclick=open;lp.insertBefore(btn,document.getElementById('close-loot'))}
  const old=window.updateInventory;if(typeof old==='function')window.updateInventory=function(){old.apply(this,arguments);renderMainInventory()};
  setInterval(()=>{if(!raid||!raid.active){initialized=false;slots=[null,null];return}ensureState();syncActive();renderMainInventory()},500);
})();